export type LyricLine = {
  /** Start time in seconds */
  t: number;
  text: string;
};

/**
 * Time-synced lyrics for each song. Times are approximate and spread across
 * each track's duration so the highlight scrolls naturally as it plays.
 * Instrumental gaps are represented by empty strings.
 */
export const lyrics: Record<string, LyricLine[]> = {
  s1: [
    { t: 0,   text: '' },
    { t: 8,   text: 'City lights blur into neon streaks' },
    { t: 16,  text: 'Midnight drive, no destination calls' },
    { t: 24,  text: 'The engine hums a quiet frequency' },
    { t: 34,  text: 'And I am weightless in the afterglow' },
    { t: 44,  text: '' },
    { t: 52,  text: 'Every mile a memory I let go' },
    { t: 62,  text: 'Every turn a sentence never said' },
    { t: 72,  text: 'The road unwinds like tape on rewind' },
    { t: 82,  text: 'And I am finally ahead of the dawn' },
    { t: 94,  text: '' },
    { t: 104, text: 'Hold the night, hold the wheel' },
    { t: 114, text: 'Let the silence sing what I feel' },
    { t: 124, text: 'Midnight drive, we are infinite' },
    { t: 140, text: 'In the quiet we are infinite' },
    { t: 160, text: '' },
    { t: 175, text: 'City lights blur into neon streaks' },
    { t: 190, text: 'And I am finally ahead of the dawn' },
    { t: 210, text: '' },
  ],
  s2: [
    { t: 0,   text: '' },
    { t: 10,  text: 'Folded wings on a windless afternoon' },
    { t: 20,  text: 'I sent a paper plane to find you' },
    { t: 30,  text: 'It curled and fell where the garden ends' },
    { t: 40,  text: 'But the sky still tasted like you' },
    { t: 52,  text: '' },
    { t: 62,  text: 'After the rain, after the rain' },
    { t: 74,  text: 'Everything softer, everything true' },
    { t: 86,  text: 'After the rain, after the rain' },
    { t: 98,  text: 'I am still learning to land without you' },
    { t: 112, text: '' },
    { t: 124, text: 'Folded wings, an older sky' },
    { t: 136, text: 'I fold the page and I let it fly' },
    { t: 150, text: 'After the rain' },
    { t: 170, text: '' },
  ],
  s3: [
    { t: 0,   text: '' },
    { t: 6,   text: 'Velvet static on the radio' },
    { t: 14,  text: 'You came in slow, a hazy wavelength' },
    { t: 22,  text: 'I tuned the dial just to keep you close' },
    { t: 32,  text: 'And the room filled up with quiet light' },
    { t: 42,  text: '' },
    { t: 50,  text: 'We are the static, we are the glow' },
    { t: 60,  text: 'Fading in, fading out, fading slow' },
    { t: 72,  text: 'Velvet static, hold me in the noise' },
    { t: 84,  text: 'Where the signal never lets us go' },
    { t: 98,  text: '' },
    { t: 110, text: 'I tuned the dial just to keep you close' },
    { t: 124, text: 'And the room filled up with quiet light' },
    { t: 145, text: '' },
  ],
  s4: [
    { t: 0,   text: '' },
    { t: 9,   text: 'Glass towers rising in the dark' },
    { t: 19,  text: 'Every window holds a different sun' },
    { t: 29,  text: 'I count the floors until I find your light' },
    { t: 39,  text: 'But the elevator only goes so far' },
    { t: 50,  text: '' },
    { t: 60,  text: 'Build me up, break me down' },
    { t: 70,  text: 'Glass towers reaching for the ground' },
    { t: 82,  text: 'Every skyline is a borrowed skyline' },
    { t: 94,  text: 'Every floor a quieter refrain' },
    { t: 108, text: '' },
    { t: 120, text: 'Glass towers rising in the dark' },
    { t: 135, text: 'I count the floors until I find your light' },
    { t: 155, text: '' },
  ],
  s5: [
    { t: 0,   text: '' },
    { t: 8,   text: 'Sundown avenue, the air turns gold' },
    { t: 18,  text: 'Bicycles lean on rusted fences' },
    { t: 28,  text: 'Someone is playing a song I used to know' },
    { t: 38,  text: 'And the evening opens like a hand' },
    { t: 50,  text: '' },
    { t: 60,  text: 'Walk me down to the long light' },
    { t: 72,  text: 'Where the day forgets to end' },
    { t: 84,  text: 'Sundown avenue, take it slow' },
    { t: 96,  text: 'We have got nowhere else to go' },
    { t: 112, text: '' },
    { t: 124, text: 'The evening opens like a hand' },
    { t: 140, text: '' },
  ],
  s6: [
    { t: 0,   text: '' },
    { t: 12,  text: 'The sky goes green, then violet, then still' },
    { t: 24,  text: 'Northern lights above the frozen bay' },
    { t: 36,  text: 'I breathe out and the cold takes shape' },
    { t: 48,  text: 'Every color is a word I never said' },
    { t: 62,  text: '' },
    { t: 76,  text: 'Hold the light, hold the night' },
    { t: 90,  text: 'Let it ripple, let it burn slow' },
    { t: 104, text: 'Northern lights, I am small beneath you' },
    { t: 120, text: 'And that is enough, that is enough' },
    { t: 140, text: '' },
    { t: 160, text: 'Every color is a word I never said' },
    { t: 185, text: '' },
  ],
  s7: [
    { t: 0,   text: '' },
    { t: 10,  text: 'I built a room out of every word you said' },
    { t: 22,  text: 'Now the echoes will not let me leave' },
    { t: 34,  text: 'I clap my hands just to hear them return' },
    { t: 46,  text: 'But the silence answers back in your voice' },
    { t: 60,  text: '' },
    { t: 72,  text: 'Echo chamber, echo chamber' },
    { t: 84,  text: 'I am living in the things you said' },
    { t: 96,  text: 'Echo chamber, echo chamber' },
    { t: 108, text: 'When do the walls come down?' },
    { t: 124, text: '' },
    { t: 138, text: 'I clap my hands just to hear them return' },
    { t: 158, text: '' },
  ],
  s8: [
    { t: 0,   text: '' },
    { t: 7,   text: 'Crystal tide pulls at the shore' },
    { t: 16,  text: 'Washing the footprints I left for you' },
    { t: 26,  text: 'Salt and light and a quiet refrain' },
    { t: 36,  text: 'The ocean remembers what I forget' },
    { t: 48,  text: '' },
    { t: 58,  text: 'Pull me out, pull me in' },
    { t: 70,  text: 'Crystal tide, where do you begin?' },
    { t: 82,  text: 'Carry me past the breakers' },
    { t: 94,  text: 'Where the water turns to glass' },
    { t: 110, text: '' },
    { t: 122, text: 'The ocean remembers what I forget' },
    { t: 138, text: '' },
  ],
  s9: [
    { t: 0,   text: '' },
    { t: 11,  text: 'Something pulls and I cannot name it' },
    { t: 23,  text: 'A slow orbit I keep returning to' },
    { t: 35,  text: 'I resist, I lean, I fall again' },
    { t: 47,  text: 'Gravity is just another word for you' },
    { t: 60,  text: '' },
    { t: 74,  text: 'Pull me down, pull me through' },
    { t: 86,  text: 'Gravity pull, I am falling into' },
    { t: 98,  text: 'A center I cannot see' },
    { t: 110, text: 'A center that is reaching for me' },
    { t: 126, text: '' },
    { t: 142, text: 'Gravity is just another word for you' },
    { t: 162, text: '' },
  ],
  s10: [
    { t: 0,   text: '' },
    { t: 9,   text: 'Golden hour, the shadows grow long' },
    { t: 19,  text: 'Honey light on an empty porch' },
    { t: 29,  text: 'I could stay here until the stars arrive' },
    { t: 39,  text: 'And even then I would not move' },
    { t: 52,  text: '' },
    { t: 62,  text: 'Hold the hour, hold the gold' },
    { t: 74,  text: 'Before it slips through my fingers again' },
    { t: 86,  text: 'Golden hour, stay a little longer' },
    { t: 98,  text: 'I am not ready for the blue' },
    { t: 114, text: '' },
    { t: 128, text: 'I could stay here until the stars arrive' },
    { t: 148, text: '' },
  ],
  s11: [
    { t: 0,   text: '' },
    { t: 14,  text: 'Deep currents move beneath the surface' },
    { t: 28,  text: 'I am learning to breathe underwater' },
    { t: 42,  text: 'The light comes down in slow green columns' },
    { t: 56,  text: 'And I let the deep carry me on' },
    { t: 72,  text: '' },
    { t: 86,  text: 'Below the noise, below the wind' },
    { t: 100, text: 'Deep currents, where do you end?' },
    { t: 114, text: 'Hold me in the quiet blue' },
    { t: 128, text: 'Hold me where the world goes still' },
    { t: 146, text: '' },
    { t: 164, text: 'I am learning to breathe underwater' },
    { t: 188, text: '' },
  ],
  s12: [
    { t: 0,   text: '' },
    { t: 12,  text: 'Neon rain on a glass arcade' },
    { t: 24,  text: 'Reflections of a city half-awake' },
    { t: 36,  text: 'I walk through color, I walk through light' },
    { t: 48,  text: 'And the rain keeps rewriting the signs' },
    { t: 62,  text: '' },
    { t: 76,  text: 'Neon rain, neon rain' },
    { t: 88,  text: 'Wash the static from my name' },
    { t: 100, text: 'Neon rain, neon rain' },
    { t: 112, text: 'I am a city you cannot erase' },
    { t: 128, text: '' },
    { t: 144, text: 'I walk through color, I walk through light' },
    { t: 162, text: 'And the rain keeps rewriting the signs' },
    { t: 185, text: '' },
  ],
};

export const lyricsForSong = (songId: string): LyricLine[] => lyrics[songId] ?? [];
